# Config file for automatic testing at travis-ci.org

sudo: true

dist: trusty

services:
  - docker

env:
  global:
    - DOCKER_REPO_URL=quay.io
    - DOCKER_REPO_OWNER=centerforopenscience
    - DOCKER_REPO_NAME=osf
    - DOCKER_BRANCH=${TRAVIS_BRANCH/\//-}
    - DOCKER_IMAGE_URL=$DOCKER_REPO_URL/$DOCKER_REPO_OWNER/$DOCKER_REPO_NAME

cache:
  directories:
    - $HOME/docker

jobs:
  include:
    - stage: Build
      script:
        - docker pull $DOCKER_IMAGE_URL:$TRAVIS_COMMIT ||
          docker pull $DOCKER_IMAGE_URL:$DOCKER_BRANCH ||
          if [ $TRAVIS_BRANCH == hotfix/* ]; then
            docker pull $DOCKER_IMAGE_URL:master;
          else
            docker pull $DOCKER_IMAGE_URL:develop;
          fi || true
        - docker build --pull
            --cache-from $DOCKER_IMAGE_URL:$TRAVIS_COMMIT --cache-from $DOCKER_IMAGE_URL:$DOCKER_BRANCH
            --cache-from $DOCKER_IMAGE_URL:master --cache-from $DOCKER_IMAGE_URL:develop
            --build-arg GIT_COMMIT=$TRAVIS_COMMIT --build-arg GIT_TAG=$TRAVIS_TAG
            -t $DOCKER_IMAGE_URL:$TRAVIS_COMMIT .
        - docker save $DOCKER_IMAGE_URL:$TRAVIS_COMMIT > $HOME/docker/image.tar
    - stage: Test
      script:
        - docker load -i $HOME/docker/image.tar
        - docker run -d --name pg postgres:9.6
        - docker run -d --name es elasticsearch:2.4
        - docker run --rm -it
            --link es --env ELASTIC_URI=es:9200
            --link pg --env OSF_DB_HOST=pg
            -v $PWD/api/base/settings/local-travis.py:/code/api/base/settings/local.py
            -v $PWD/website/settings/local-travis.py:/code/website/settings/local.py
            $DOCKER_IMAGE_URL:$TRAVIS_COMMIT invoke test_travis_osf -n 4
    - script:
        - docker load -i $HOME/docker/image.tar
        - docker run -d --name pg postgres:9.6
        - docker run -d --name es elasticsearch:2.4
        - docker run --rm -it
            --link es --env ELASTIC_URI=es:9200
            --link pg --env OSF_DB_HOST=pg
            -v $PWD/api/base/settings/local-travis.py:/code/api/base/settings/local.py
            -v $PWD/website/settings/local-travis.py:/code/website/settings/local.py
            $DOCKER_IMAGE_URL:$TRAVIS_COMMIT invoke test_travis_else -n 4
    - script:
        - docker load -i $HOME/docker/image.tar
        - docker run -d --name pg postgres:9.6
        - docker run -d --name es elasticsearch:2.4
        - docker run --rm -it
            --link es --env ELASTIC_URI=es:9200
            --link pg --env OSF_DB_HOST=pg
            -v $PWD/api/base/settings/local-travis.py:/code/api/base/settings/local.py
            -v $PWD/website/settings/local-travis.py:/code/website/settings/local.py
            $DOCKER_IMAGE_URL:$TRAVIS_COMMIT invoke test_travis_api1 -n 4
    - script:
        - docker load -i $HOME/docker/image.tar
        - docker run -d --name pg postgres:9.6
        - docker run -d --name es elasticsearch:2.4
        - docker run --rm -it
            --link es --env ELASTIC_URI=es:9200
            --link pg --env OSF_DB_HOST=pg
            -v $PWD/api/base/settings/local-travis.py:/code/api/base/settings/local.py
            -v $PWD/website/settings/local-travis.py:/code/website/settings/local.py
            $DOCKER_IMAGE_URL:$TRAVIS_COMMIT invoke test_travis_api2 -n 4
    - script:
        - docker load -i $HOME/docker/image.tar
        - docker run -d --name pg postgres:9.6
        - docker run -d --name es elasticsearch:2.4
        - docker run --rm -it
            --link es --env ELASTIC_URI=es:9200
            --link pg --env OSF_DB_HOST=pg
            -v $PWD/api/base/settings/local-travis.py:/code/api/base/settings/local.py
            -v $PWD/website/settings/local-travis.py:/code/website/settings/local.py
            $DOCKER_IMAGE_URL:$TRAVIS_COMMIT invoke test_travis_api3 -n 4
    - stage: Push
      script:
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$DOCKER_USERNAME" ] && [ ! -z "$DOCKER_PASSWORD" ]; then
            docker load -i $HOME/docker/image.tar;
            travis_retry docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REPO_URL;
            docker tag $DOCKER_IMAGE_URL:$TRAVIS_COMMIT $DOCKER_IMAGE_URL:$DOCKER_BRANCH;
            docker push $DOCKER_IMAGE_URL:$TRAVIS_COMMIT;
            docker push $DOCKER_IMAGE_URL:$DOCKER_BRANCH;
          fi
        - rm -f $HOME/docker/image.tar;

branches:
  except:
    - /^[0-9]/

notifications:
  flowdock: 0221882cdda034c0e9ac2a0e766053dd
